print("Ahoj")
print(2)
print(2+3+5)
print("x")
# print(1+e)
print(1, "ahos", "sdsdf")
print(3*5 + 5*7)
print("Ctverec o straně 457 cm má obvod",4*457,"cm a obsah",457*457,"cm^2")
a = input("Zadej číslo:")
print(a)
print(type(a))
a = int(a)
print(a)
print(type(a))
a = int(input("Zadej číslo"))
print(type(True))